### ISSUE TITLE
Doesn't install itself

### ISSUE THREAD

**Issue by Finesse** [ameyp-nodejs/gulp-optipng#2]
I try to install `gulp-optipng` using NPM. There is an error during `npm install gulp-optipng` execution:

```
> optipng-bin@0.3.11 postinstall ~/src/node_modules/optipng-stream-bin/node_modules/optipng-bin
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/optipng-bin/v0.3.11/vendor/osx/optipng',
  name: 'optipng',
  os: 'darwin' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at ~/src/node_modules/optipng-stream-bin/node_modules/download/index.js:35:43
    at each (~/src/node_modules/optipng-stream-bin/node_modules/each-async/each-async.js:63:4)
    at module.exports (~/src/node_modules/optipng-stream-bin/node_modules/download/index.js:33:5)
    at ~/src/node_modules/optipng-stream-bin/node_modules/bin-wrapper/index.js:108:20
    at ~/src/node_modules/optipng-stream-bin/node_modules/bin-wrapper/index.js:141:24
    at ~/src/node_modules/optipng-stream-bin/node_modules/bin-check/index.js:30:20
    at ~/src/node_modules/optipng-stream-bin/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:123:15)
```

And:

```
npm ERR! optipng-bin@0.3.11 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the optipng-bin@0.3.11 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the optipng-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs optipng-bin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls optipng-bin
npm ERR! There is likely additional logging output above.
```

OS: OS X 10.11.6.

Maybe you should try to include more fresh optipng as a package dependency because optipng itself is installed successfully.

**Comment by insanityfarm** [comment]
I am also encountering this. Are there any known workarounds?

Edit: I wanted to add that this happened on my Mac as well (10.12.1). However, the same package installed without issue within my Ubuntu VM. So it would seem to be a platform-specific issue.

Edit 2: Actually, this could be a Node version issue. I'm running v7.0.0 on my Mac, and v5.0.0 in the Ubuntu VM. I just recalled encountering [this issue in another package](https://github.com/floridoo/gulp-sourcemaps/issues/192) a few months ago, in which a similar error was presented in node v6 and up.

**Comment by insanityfarm** [comment]
Update: I just found that @dasoft forked gulp-optipng a few months ago to fix this issue: https://github.com/dasoft/gulp-optipng

I have validated his fix on my Node 7 system. Doesn't look like a PR was created and this original repo may no longer be maintained anyway. Shame! Thanks dasoft for your fix. I was able to change my project's existing dependency from...

`"gulp-optipng": "^0.0.2"`

...to...

`"gulp-optipng": "git+https://github.com/dasoft/gulp-optipng.git"`

...if anyone is looking for an immediate fix they can use.
